// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuP0EkETkWMR7b_ZBv-jT0dC74gZVapmI',
    appId: '1:448894820971:web:5dea0374dfc4cbff22872e',
    messagingSenderId: '448894820971',
    projectId: 'brightside-9a2c5',
    authDomain: 'brightside-9a2c5.firebaseapp.com',
    storageBucket: 'brightside-9a2c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuP0EkETkWMR7b_ZBv-jT0dC74gZVapmI',
    appId: '1:448894820971:android:5dea0374dfc4cbff22872e',
    messagingSenderId: '448894820971',
    projectId: 'brightside-9a2c5',
    storageBucket: 'brightside-9a2c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuP0EkETkWMR7b_ZBv-jT0dC74gZVapmI',
    appId: '1:448894820971:ios:5dea0374dfc4cbff22872e',
    messagingSenderId: '448894820971',
    projectId: 'brightside-9a2c5',
    storageBucket: 'brightside-9a2c5.firebasestorage.app',
    iosBundleId: 'com.example.brightside',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuP0EkETkWMR7b_ZBv-jT0dC74gZVapmI',
    appId: '1:448894820971:macos:5dea0374dfc4cbff22872e',
    messagingSenderId: '448894820971',
    projectId: 'brightside-9a2c5',
    storageBucket: 'brightside-9a2c5.firebasestorage.app',
    iosBundleId: 'com.example.brightside',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuP0EkETkWMR7b_ZBv-jT0dC74gZVapmI',
    appId: '1:448894820971:windows:5dea0374dfc4cbff22872e',
    messagingSenderId: '448894820971',
    projectId: 'brightside-9a2c5',
    authDomain: 'brightside-9a2c5.firebaseapp.com',
    storageBucket: 'brightside-9a2c5.firebasestorage.app',
  );
}
